version: '3.4'

services:
  gittest:
    image: gittest
    hostname: gittest
    container_name: gittest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./src:/usr/src/app/src
    #command: sh -c "npm start"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
